DROP TABLE if exists survey_clean;
CREATE EXTERNAL TABLE survey_clean
(provider_id int,
hospital_name string,
address string,
city string,
state_abbrev string,
zip_code int,
county string,
nurses_achievement int,
nurses_improvement int,
nurses_dimension int,
doctors_achievement int,
doctors_improvement int,
doctors_dimesion int,
responsiveness_achievement int,
responsiveness_improvement int,
responsiveness_dimension int,
pain_achievement int,
pain_improvement int,
pain_dimension int,
communication_achievement int,
communication_improvement int,
communication_dimension int,
cleanliness_achievement int,
cleanliness_improvement int,
cleanliness_dimension int,
discharge_achievement int,
discharge_improvement int,
discharge_dimension int,
overall_achievement int,
overall_improvement int,
overall_dimension int,
HCAHPS_base_score int,
HCAHPS_base_consistency int,
measure_start date,
measure_end date)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/raw_data/survey';

INSERT OVERWRITE TABLE survey_clean
SELECT
provider_id,
hospital_name,
address,
city,
state_abbrev,
zip_code,
county,
SUBSTR(nurses_achievement,1,2),
SUBSTR(nurses_improvement,1,2),
SUBSTR(nurses_dimension,1,2),
SUBSTR(doctors_achievement,1,2),
SUBSTR(doctors_improvement,1,2),
SUBSTR(doctors_dimesion,1,2),
SUBSTR(responsiveness_achievement,1,2),
SUBSTR(responsiveness_improvement,1,2),
SUBSTR(responsiveness_dimension,1,2),
SUBSTR(pain_achievement,1,2),
SUBSTR(pain_improvement,1,2),
SUBSTR(pain_dimension,1,2),
SUBSTR(communication_achievement,1,2),
SUBSTR(communication_improvement,1,2),
SUBSTR(communication_dimension,1,2),
SUBSTR(cleanliness_achievement,1,2),
SUBSTR(cleanliness_improvement,1,2),
SUBSTR(cleanliness_dimension,1,2),
SUBSTR(discharge_achievement,1,2),
SUBSTR(discharge_improvement,1,2),
SUBSTR(discharge_dimension,1,2),
SUBSTR(overall_achievement,1,2),
SUBSTR(overall_improvement,1,2),
SUBSTR(overall_dimension,1,2),
SUBSTR(HCAHPS_base_score,1,2),
SUBSTR(HCAHPS_base_consistency,1,2),
measure_start,
measure_end
FROM survey;

